# Site settings
title: Xing Shi
email: xingshi@usc.edu
description: "Xing Shi's homepage, Information Sciences Institute / University of Southern California (ISI/USC)"
baseurl: ""
url: "http://xingshi.me"

# Build settings
markdown: kramdown
permalink: pretty
