# Site settings
title: Xing Shi
email: xingshi@usc.edu
description: "Xing Shi's homepage, a Ph.D. student at Department of Computer Science of University of Southern California."
baseurl: ""
url: "http://xingshi.me"

# Build settings
markdown: kramdown
permalink: pretty
